### ISSUE TITLE
Not updated on Arduino Library Manager

### ISSUE THREAD

**Issue by alexfandos** [tomstewart89/Callback#6]
Arduino Library Manager downloads versión 1.0 which uses Connect and Emit instead of Attach and Fire.

Should I use version 1.0 from the Library Manager or the GitHub's 1.1 version?

**Comment by tomstewart89** [comment]
Hey Alex, thanks for the info, I wasn't aware that the version manager was out of date. I'll update it when I get the chance but in the meantime go with v1.1

**Comment by tomstewart89** [comment]
Sorry for the super slow response, I just made a release for v1.1 so this should be resolved now!
